POST http://localhost:3000/usuarios HTTP/1.1
content-type: application/json

{
  "nome": "Alexandre Oliveira",
  "email": "alexandre1212@alura.com.br",
  "senha": "123123"
}

# {
#   "nome": "Gustavo Paiva",
#   "email": "gu.paiva@alura.com.br",
#   "senha": "123123"
# }

# {
#   "nome": "Leonardo Pereira",
#   "email": "leo1990@alura.com.br",
#   "senha": "123123"
# }

###busca usuario
GET http://localhost:3000/usuarios HTTP/1.1
content-type: application/json


###atualiza usuario - colocar o id do usuario depois do usuarios/
PUT http://localhost:3000/usuarios/61c3bf0e-8eb5-4123-a7a2-c9a4cfdff398 HTTP/1.1
content-type: application/json

{
  "nome": "Leonardo da Silva Pereira"
}


###deleta usuario - colocar o id do usuario depois do usuarios/
DELETE http://localhost:3000/usuarios/ HTTP/1.1
content-type: application/json
