### Deposit
POST http://localhost:3000/deposit HTTP/1.1
content-type: application/json

# {
#     "input" : {
#         "account_id": "2ba8924a-a937-4964-8271-728caab4da80",
#         "amount": 100
#     }
# }

{
    "input" : {
        "account_id": "ec421ab4-c5e0-4314-b0c0-5463259dd7c7",
        "amount": 100
    }
}